[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"

[[repos.hooks]]
id = "trailing-whitespace"
exclude = "(.*\\.md$|^docs/_build/)"

[[repos.hooks]]
id = "end-of-file-fixer"
exclude = "(.*\\.md$|^docs/_build/)"

[[repos.hooks]]
id = "check-yaml"

[[repos.hooks]]
id = "check-toml"

[[repos.hooks]]
id = "check-added-large-files"
exclude = "^uv\\.lock$"

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "v1.7.12"

[[repos.hooks]]
id = "actionlint"
additional_dependencies = [
  "github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.11.1",
]

[[repos]]
repo = "https://github.com/codespell-project/codespell"
rev = "v2.4.3"

[[repos.hooks]]
id = "codespell"
args = ["--ignore-words-list=hass,IST"]
exclude = "^docs/_build/"

[[repos]]
repo = "local"

[[repos.hooks]]
id = "mypy"
name = "mypy"
language = "system"
entry = "uv run --exact --group dev mypy --config-file=pyproject.toml"
types = ["python"]
require_serial = true

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.16.1"

[[repos.hooks]]
id = "ruff-check"
args = ["--fix"]

[[repos.hooks]]
id = "ruff-format"
