substitutions:
  device_name: rtl433-heltec-lora-32-v2
  friendly_name: rtl433_esphome heltec_lora_32_v2
  fallback_ssid: rtl433_esphome Fallback
  rtl433_esphome_url: https://github.com/Snuffy2/rtl433_esphome.git
  rtl433_esphome_ref: latest

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: "Heltec WiFi LoRa 32 V2 rtl_433 ESPHome gateway"
  devices:
    - id: garage_fridge_device
      name: Garage Fridge
    - id: garage_freezer_device
      name: Garage Freezer

esp32:
  board: heltec_wifi_kit_32_v2
  framework:
    type: arduino

logger:

api:

time:
  - platform: homeassistant
    id: homeassistant_time

ota:
  - platform: esphome
    on_begin:
      - rtl433_native.stop: rtl433_gateway

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${fallback_ssid}"
    password: !secret fallback_ap_password

captive_portal:

external_components:
  - source:
      type: git
      url: ${rtl433_esphome_url}
      ref: ${rtl433_esphome_ref}
    refresh: never
    components:
      - rtl433_native

rtl433_native:
  id: rtl433_gateway
  time_id: homeassistant_time
  candidate_limit: 10
  stale_after: 1h
  known_sensors:
    - key: garage_fridge
      device_id: garage_fridge_device
      mapping: "LaCrosse-TX141THBv2/0/203;TFA-303221/1/203"
      entities:
        - temperature
        - humidity
        - battery
        - rssi
        - stale
        - last_updated
        - mapping
    - key: garage_freezer
      device_id: garage_freezer_device
      mapping: "TFA-303221/2/88;LaCrosse-TX141THBv2/1/88"
      entities:
        - temperature
        - humidity
        - battery
        - rssi
        - stale
        - last_updated
        - mapping
sensor:
  - platform: uptime
    name: "Uptime"
    entity_category: diagnostic
  - platform: wifi_signal
    name: "Wi-Fi RSSI"
    update_interval: 120s
    entity_category: diagnostic
  - platform: template
    name: "Free Heap"
    accuracy_decimals: 0
    unit_of_measurement: "B"
    update_interval: 120s
    lambda: return ESP.getFreeHeap();
    entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: 'IP Address'
      icon: mdi:ip-network
      entity_category: diagnostic

binary_sensor:
  - platform: status
    name: 'Status'
    entity_category: diagnostic

button:
  - platform: restart
    name: Restart
    icon: mdi:restart
    entity_category: config
